project:
  type: website
  title: "Outil d'auto-diagnostic"

website:
  back-to-top-navigation: true
  navbar:
    title: "<a href='https://cc-hautpoitou.fr/' target='_blank'><img class='navbar-logo' src='images/logos/Cc-du-haut-poitou-logo.png' height='90px'></a>"
    #logo: "images/logos/Cc-du-haut-poitou-logo.png"
    logo-alt: "CC du Haut Poitou"
    left:
      - href: index.qmd
        text: Accueil
        icon: house
      - about.qmd
      
  page-footer:
    left: "Site créé avec [Quarto](https://quarto.org/)"
    center: "©CEREMA"
    right: 
      - icon: linkedin
        href: https://fr.linkedin.com/company/cerema
      - icon: twitter-x 
        href: https://x.com/ceremacom
      - icon: youtube
        href: https://www.youtube.com/@cerema3139 

format:
  html:
    theme: cosmo
    css: styles.css
    #toc: true
    #toc-location: left
    #toc-depth: 2
    
editor: visual

