---
format: html
---

<strong style='color: #2c3771;
                    font-size: 18px;
                    position: relative;
                    left: 39%;
                    -webkit-transform: translateX(-50%);
                    transform: translateX(-50%);
                    width: 100px;
                    height: 1px;
                    background: #dee2e6;
                    padding: 5px;
                    border-radius: 15px;'>Question 6 sur 10</strong>

<div style='text-align: left; margin-bottom: 20px;'>
<button onclick="window.location.href='question_5.html'" style='background-color: red; color: white; border: none; padding: 10px; border-radius: 5px; cursor: pointer;'>Précédent</button>
</div>

## Réalisez-vous une veille sur l'évolution de la réglementation environnementale liée à vos activités ?

### Sélectionnez votre réponse :

- [ ] Oui nous avons mis en place une veille rigoureuse en interne sur la réglementation environnementale

- [ ] Oui nous nous appuyons sur un dispositif externalisé de veille (prestation, abonnement, etc.)

- [ ] Nous suivons l'évolution de la réglementation environnementale mais de manière partielle et lacunaire

- [ ] Non

<br>
<button id='continuer' onclick='sauvegarderReponses()' style='color: #932020; border: none; padding: 10px; border-radius: 5px; cursor: pointer; margin-right: 10px;'>Continuer plus tard</button>
<button onclick="window.location.href='question_7.html'" style='background-color: red; color: white; border: none; padding: 10px; border-radius: 5px; cursor: pointer;' >Suivant</button>


<script>
document.getElementById('quiz-form').addEventListener('submit', function(event) {
  event.preventDefault();
  let responses = [];
  document.querySelectorAll('input[type=checkbox]:checked').forEach((checkbox) => {
    responses.push(checkbox.value);
  });
  localStorage.setItem('reponses_q6', JSON.stringify(responses));
  alert('Réponse enregistrée !');
});
function sauvegarderReponses() {
  let responses = [];
  document.querySelectorAll('input[type=checkbox]:checked').forEach((checkbox) => {
    responses.push(checkbox.value);
  });
  localStorage.setItem('reponses_q6', JSON.stringify(responses));
  alert('✔ Réponses enregistrées ! Vous pouvez revenir plus tard.');
 window.location.href = 'index.html'; }
</script>

