---
format: html
---

<strong style='color: #2c3771;
                    font-size: 18px;
                    position: relative;
                    left: 39%;
                    -webkit-transform: translateX(-50%);
                    transform: translateX(-50%);
                    width: 100px;
                    height: 1px;
                    background: #dee2e6;
                    padding: 5px;
                    border-radius: 15px;'>Question 4 sur 10</strong>

<div style='text-align: left; margin-bottom: 20px;'>
<button onclick="window.location.href='question_3.html'" style='background-color: red; color: white; border: none; padding: 10px; border-radius: 5px; cursor: pointer;'>Précédent</button>
</div>

## Avez-vous mis en place des outils de pilotage et de suivi des impacts environnementaux de vos activités, produits et services (ex: vos émissions de GES, vos consommations d'eau et d'énergie, votre impact sur la biodiversité...) ?

### Sélectionnez votre réponse :

- [ ] Oui nous avons mis en place une démarche rigoureuse de suivi et réduction de nos différents impacts environnementaux (diagnostics, tableaux de bord, indicateurs, etc.)

- [ ] Nous connaissons nos principaux impacts environnementaux mais nous n'avons pas mis en place de suivi précis, ni régulier de ces derniers (diagnostic réalisé mais pas d'outils de suivi précis dans la durée)

- [ ] Nous ne connaissons pas bien les impacts environnementaux de notre activité et nous n'avons aucun outil de pilotage, ni de suivi de ces derniers

<br>
<button id='continuer' onclick='sauvegarderReponses()' style='color: #932020; border: none; padding: 10px; border-radius: 5px; cursor: pointer; margin-right: 10px;'>Continuer plus tard</button>
<button onclick="window.location.href='question_5.html'" style='background-color: red; color: white; border: none; padding: 10px; border-radius: 5px; cursor: pointer;' >Suivant</button>


<script>
document.getElementById('quiz-form').addEventListener('submit', function(event) {
  event.preventDefault();
  let responses = [];
  document.querySelectorAll('input[type=checkbox]:checked').forEach((checkbox) => {
    responses.push(checkbox.value);
  });
  localStorage.setItem('reponses_q4', JSON.stringify(responses));
  alert('Réponse enregistrée !');
});
function sauvegarderReponses() {
  let responses = [];
  document.querySelectorAll('input[type=checkbox]:checked').forEach((checkbox) => {
    responses.push(checkbox.value);
  });
  localStorage.setItem('reponses_q4', JSON.stringify(responses));
  alert('✔ Réponses enregistrées ! Vous pouvez revenir plus tard.');
 window.location.href = 'index.html'; }
</script>

