---
format: html
---

<strong style='color: #2c3771;
                    font-size: 18px;
                    position: relative;
                    left: 39%;
                    -webkit-transform: translateX(-50%);
                    transform: translateX(-50%);
                    width: 100px;
                    height: 1px;
                    background: #dee2e6;
                    padding: 5px;
                    border-radius: 15px;'>Question 2 sur 10</strong>

<div style='text-align: left; margin-bottom: 20px;'>
<button onclick="window.location.href='question_1.html'" style='background-color: red; color: white; border: none; padding: 10px; border-radius: 5px; cursor: pointer;'>Précédent</button>
</div>

## Une (ou plusieurs) personne au sein de votre structure est-elle "référente/pilote" sur le suivi des impacts environnementaux de votre activité ?

### Sélectionnez votre réponse :

- [ ] Oui une personne (ou plusieurs) est chargée, à temps plein, de suivre nos impacts environnementaux (indiquez le nom de la (ou les) personne et son niveau de responsabilité)

- [ ] Oui, une personne est en charge de suivre nos impacts environnementaux mais cela ne représente qu'une petite partie de ses missions (indiquez le nom de la personne et son niveau de responsabilité)

- [ ] Non

<br>
<button id='continuer' onclick='sauvegarderReponses()' style='color: #932020; border: none; padding: 10px; border-radius: 5px; cursor: pointer; margin-right: 10px;'>Continuer plus tard</button>
<button onclick="window.location.href='question_3.html'" style='background-color: red; color: white; border: none; padding: 10px; border-radius: 5px; cursor: pointer;' >Suivant</button>


<script>
document.getElementById('quiz-form').addEventListener('submit', function(event) {
  event.preventDefault();
  let responses = [];
  document.querySelectorAll('input[type=checkbox]:checked').forEach((checkbox) => {
    responses.push(checkbox.value);
  });
  localStorage.setItem('reponses_q2', JSON.stringify(responses));
  alert('Réponse enregistrée !');
});
function sauvegarderReponses() {
  let responses = [];
  document.querySelectorAll('input[type=checkbox]:checked').forEach((checkbox) => {
    responses.push(checkbox.value);
  });
  localStorage.setItem('reponses_q2', JSON.stringify(responses));
  alert('✔ Réponses enregistrées ! Vous pouvez revenir plus tard.');
 window.location.href = 'index.html'; }
</script>

